apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-secret
data:
  JWT_SECRETKEY:  {{ .Values.adminConfig.JWTSecret | b64enc | quote }}
  DATASOURCE_POSTGRESCONFIG: {{ printf "host=%s-%s port=%s user=%s password=%s dbname=%s" .Release.Name .Values.adminConfig.POSTGRES_DB_SERVER .Values.adminConfig.POSTGRES_DB_PORT .Values.postgresql.auth.username .Values.postgresql.auth.password .Values.postgresql.auth.database | b64enc | quote }}

