apiVersion: v2
name: observability-charts
version: 0.0.1
sources:
  - https://github.com/KumKeeHyun/go-gin-realworld-example-app
dependencies:
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 48.3.1
    condition: kube-prometheus-stack.enabled
  - name: kibana
    repository: https://helm.elastic.co
    version: 7.17.3
    condition: kibana.enabled
  - name: elasticsearch
    repository: https://helm.elastic.co
    version: 7.17.3
    condition: elasticsearch.enabled
  - name: fluentd
    repository: https://fluent.github.io/helm-charts
    version: 0.4.3
    condition: fluent.enabled